user_input = input("Введите последовательность чисел через пробел: ")
numbers_list = user_input.split()
numbers_tuple = tuple(numbers_list)
print("Список:", numbers_list)
print("Кортеж:", numbers_tuple)
